# Generated by Django 4.2.23 on 2025-08-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_college_is_active_and_more'),
        ('students', '0002_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.AddField(
            model_name='student',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_panel.examschedule'),
        ),
    ]
