# Generated by Django 4.2.23 on 2025-09-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_examschedulehistory'),
        ('students', '0003_remove_student_college_student_exam_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_panel.examschedulehistory'),
        ),
    ]
