# Generated by Django 4.2.23 on 2025-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_exam_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_ticket',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
