# Generated by Django 4.2.23 on 2026-08-04 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')]),
        ),
    ]
