# Generated by Django 4.2.23 on 2026-08-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_examschedule_unique_together_and_more'),
        ('students', '0008_alter_student_email_student_unique_email_per_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admin_panel.examschedulehistory'),
        ),
    ]
