# Generated by Django 4.2.23 on 2026-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_exam_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
