# Generated by Django 4.2.23 on 2026-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_roll_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_email_per_exam',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email', 'exam_schedule', 'mobile_number'), name='unique_email_per_exam'),
        ),
    ]
