# Generated by Django 4.2.23 on 2026-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_unique_email_per_exam_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_email_per_exam',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('email', 'exam_schedule'), name='unique_email_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_no', 'mobile_number', 'exam_schedule'), name='unique_rollmobile_per_exam'),
        ),
    ]
