# Generated by Django 4.2.23 on 2026-10-01 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_unique_email_per_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_degree',
            field=models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('BCA', 'BCA'), ('BSCIT', 'B.Sc. IT')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='masters_degree',
            field=models.CharField(blank=True, choices=[('MCA', 'MCA'), ('MSCIT', 'M.Sc. IT'), ('MTECH', 'M.Tech')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='masters_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
