# Generated by Django 4.2.23 on 2025-08-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('quiz_enabled', models.BooleanField(default=False)),
                ('quiz_date', models.DateField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('quiz_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
