# Generated by Django 4.2.23 on 2025-08-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='college',
            name='official_email',
        ),
        migrations.RemoveField(
            model_name='college',
            name='official_name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='quiz_date',
        ),
        migrations.RemoveField(
            model_name='college',
            name='quiz_enabled',
        ),
        migrations.RemoveField(
            model_name='college',
            name='quiz_link',
        ),
        migrations.RemoveField(
            model_name='college',
            name='registration_enabled',
        ),
        migrations.RemoveField(
            model_name='college',
            name='registration_link',
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CollegeOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='admin_panel.college')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True)),
                ('quiz_enabled', models.BooleanField(default=False)),
                ('quiz_date', models.DateField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('quiz_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='admin_panel.college')),
            ],
            options={
                'unique_together': {('college', 'quiz_date')},
            },
        ),
    ]
