# Generated by Django 4.2.23 on 2025-08-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_college_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='quiz_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
