# Generated by Django 4.2.23 on 2025-08-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_examschedule_quiz_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.college')),
            ],
            options={
                'ordering': ['-quiz_date'],
            },
        ),
    ]
