# Generated by Django 4.2.23 on 2026-08-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_examschedulehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='current_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointed_to_by', to='admin_panel.examschedulehistory'),
        ),
        migrations.AddField(
            model_name='examschedulehistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examschedulehistory',
            name='quiz_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examschedulehistory',
            name='registration_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule', to='admin_panel.college'),
        ),
        migrations.AlterField(
            model_name='examschedulehistory',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admin_panel.college'),
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='quiz_date',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='quiz_enabled',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='registration_enabled',
        ),
    ]
