# Generated by Django 4.2.23 on 2026-09-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_examschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(choices=[('CHD', 'Chandigarh'), ('BBSR', 'Bhubaneswar')], default='CHD', max_length=10),
        ),
    ]
