# Generated by Django 4.2.23 on 2025-11-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_submitted_at_result_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
