# Generated by Django 4.2.23 on 2026-08-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_mobile_number'),
        ('tests', '0005_question_created_at_question_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='students.student')),
            ],
        ),
    ]
