# Generated by Django 4.2.23 on 2026-09-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_result_exam_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technical'), ('REAS', 'Reasoning'), ('DB', 'Database'), ('AI', 'Artificial Intelligence')], max_length=4),
        ),
    ]
